### ISSUE TITLE
[todo] 210814

### ISSUE THREAD

**Issue by c1ino** [c1ino/c1ino#1]
### py语法
- [ ] #2
  - 词法域、自由变量、绑定变量、语法块语法结构、变量提升
- [ ] #5
- [ ] #7
- [ ] py语法结构与代码对象与帧栈回溯
- [ ] py语法、词法成分

### py文法 
- [ ] #3
- [ ] #4
  - 安装到分发、另见、py包开发到项目构建、项目依赖管理、冻结编译打包、歧义、安装路径、分发包格式、软件包元信息、包管理、构建目标
- [ ] #6
- [ ] #8

-----
- [ ] #9
- [ ] 表达式与前中后缀与主谓宾
  - 波兰表达式、s-表达式、运算符中缀表达式、函数调用前缀表达式、链式后缀表达式
---
-  ~~dispatch、delegate~~
- [ ] inst-bound-method
- [ ] cps、anf、callback
  - promise-chain、pipe 、TCO
- [ ] class-declare-namespace-super
-  ~~js tagged template~~

**Comment by c1ino** [comment]
- [ ] py的用且只用一种最佳明确方法与不止一种方法
- [ ] py内置类型方法的风格与函数式副作用与一致性
  - 副作用（原地修改）的优点是节省内存（https://docs.python.org/zh-cn/3/faq/design.html#why-doesn-t-list-sort-return-the-sorted-list ）
- [ ] py推导式局限性
  - 不能break/continue
  - 不能使用赋值表达式
  - yield？
- [x] py自定义导入系统及初始化
  - PEP 648、customize、*.pth、sys.meta_path/path_hooks/paths
  - `python -m site`
  - #3
  - #6

**Comment by c1ino** [comment]
- [ ] py元编程属性查找机制有什么用：委派转发属性访问
  - 策略模式、状态模式 、“模拟类函数逆向继承”
  - 将实例属性访问代理到另一个类对象中去：https://python3-cookbook.readthedocs.io/zh_CN/latest/c08/p15_delegating_attribute_access.html
  - “基于动态委派的方法重载”
  - “基于描述器的将特定方法调用动态委托给其他类”（而非实例对象，类似super()）
  - mixin、inheritance、trait、dispatch、delegeate、proxy、strategy、state、interface
  - 代理描述器，将实例的方法调用动态委托给另一个类对象，类对象取决于实例的特定属性值
    - proxy descriptor that dynamically delegates method calls of the instance to another class depends on specific attribute 
  - switch-stmts-by-pseudo-state-machine-class
  - method = dispatchmethod('property_to_targetclass')
  - `@dynamicdispatch` `@propertydispatch` `@sharemethod` 
    - `@mixinmethod` `@traitmethod`
  - https://pypi.org/project/superdelegate/

**Comment by c1ino** [comment]
- [x] py依赖系统与包管理pip
  - 依赖安装级别、installation scheme：
    - 环境级：系统全局(site/venv)、用户目录(--user)
    - 项目级：本地目录(--target)
  - 环境级依赖用虚拟环境(venv)或者虚拟机解决，比如轻量级虚拟机docker
    - 虚拟环境不可移动分发
    - 虚拟机容器镜像可以分发
  - 项目级依赖用虚拟环境或者本地安装解决，比如pip所使用的内部静态依赖vendor
  - 模块分工
    - 导入与导入路径(import)：site、importlib
    - 安装与安装路径(install)：sysconfig、distutils、setuptools、pip
  - #6

**Comment by c1ino** [comment]
- [ ] py/js函数式
  - curry、pointfree、partial/bind/left/right、higher-order
  - map、filter、reduce
  - compose/flow/pipeline、infix-operator、chain、tail-call-optimization
    - collection-pipeline
  - 纯函数与副作用与IO
  - 范畴论？组合子？lambda？ 
    - 无状态、并发

https://eli.thegreenplace.net/2017/on-recursion-continuations-and-trampolines/

**Comment by c1ino** [comment]
- [ ] [draft] py导入与安装机制 import/install

**Comment by c1ino** [comment]
- [ ] py顶层模块、入口模块、入口函数、主模块、主函数
  - __name__、__main__.py、pkg.mod:func
  - int main(){}
- [ ] py模块对象、模块与导入机制、模块属性、加载机制、重载reload
  - spec、loader、create_module、exec_module
  - name, file, package, path, spec, loader, doc
  - all, dir, getattr
  - class, types.Module; instance, dict/vars

**Comment by c1ino** [comment]
- #9 
- [x] asyncio浅谈 
  - asyncio本质上是转让控制权，关键在于何时when和怎样how。答案是在IO操作的时候。也就是针对IO密集，而不是CPU密集。
  - 协程可能没有标准的定义与实现，所以各语言之间的协程可能小同大异。很难统一分类，比如对称协程/非对称协程、有无调用栈、有无内部栈帧、有无独立线程栈、（I/O多路复用）。
    - 有栈协程是全局yield（调用栈/gevent），无栈协程是局部yield（函数内部/async-def）
      - stackfull, stackless
      - 基于调用栈的协程，基于生成器的半协程
    - 生成器是对称协程？yield from是非对称协程？
    - 线程基于系统线程，但是协程没有系统协程可做标准。
  - 同步调用链、异步协程链
    - 调用链从栈顶指向栈底、从内指向外。协程链从栈底指向栈顶、从外指向内。
  - （半）协程与生成器的区别
    - 生成器可以被多个函数yield from，协程只能被一个父协程await
    - 协程支持生成器协议send/throw/close
    - 协程不支持迭代器协议__iter__/`__next__`/iter()/next()
  - 协议：await语句与__await__魔术方法
    - `__await__`等价于__iter__，返回值是一个协程/生成器，支持生成器协议send/throw/close
    - await语句调用对象的__await__方法，等待的是方法所返回的协程
  - 生成器的限制
    - 生成器内部无法直接获取自身，也无法直接获取父生成器
      - 可以获取函数调用栈帧，但无法通过栈帧获取生成器，反之可以通过生成器获取对应帧
  - 优劣
    - 轻量级上下文切换？
    - 轻量级内存开销/成本
    - 伪并行、单线程异步
  - 控制权
    - yield 转移给调用者，yield from 单向转移给子协程
    - 生成器/半协程以函数为单位，协程/微线程以线程栈为单位
  - 异步、惰性计算、并行计算、函数式
  - 无栈协程如何实现协程链？_lasti+_frame+_yieldfrom？
### 另见
https://snarky.ca/how-the-heck-does-async-await-work-in-python-3-5/ 

https://www.youtube.com/watch?v=M-UcUs7IMIM

**Comment by c1ino** [comment]
- [ ] makefile 笔记
  - GNU, POSIX, ...
  - target/pattern, reqs, cmds/receipe
    - target: file/path-pattern, phony
  - autoconf/configure
  - file-system-namespace, Call-by-reference
    - 文件系统/IPC
  - deps-tree, pattern-match
  - workflow
  - limit
    - 针对文件编译构建的工作流
    - （shell）不支持（父进程shell）脚本环境（被子进程）修改
  - promise.gather(*tasks)
  - receipe(makefile), stage(target), preqs, steps(cmds), Ingredients(files)
  - formula(target), target, material(files), steps(cmds)
    - materials + steps = target

**Comment by c1ino** [comment]
- [ ] py 作用域及作用范围
  - 作用域：函数/匿名函数、类定义、模块
    - 其他复合语句/代码块没有作用域
    - （特殊作用域？推导式、生成器表达式） 
  - break/continue/return/yield：函数内，不可传递到函数外
    - （如果是有栈协程，yield可以传递到函数外，暂停整个调用栈）
  - raise：可传递到函数外
- [ ] py自省/反射限制
  - 自省
    - 函数内部无法获得函数对象自身
    - 生成器内部无法获得生成器对象自身
    - 类定义作用域无法直接访问类自身以及父类（但父类可以通过全局名称间接访问）
    - 非赋值语句中的表达式产生的对象不可二次访问
    - 函数内部无法获取函数对象自身的名字（但可以通过函数的全局名称动态访问）
      - （https://docs.python.org/zh-cn/3/faq/programming.html#how-can-my-code-discover-the-name-of-an-object ）
      - 但可以通过当前帧对应的代码对象f_code获取代码对象的名称/函数名co_name
    - 原理上与实例方法相似，实例方法无法直接访问类或者实例对象，必须通过参数中的self获取。
    - 反过来说，如果函数能够直接获取函数对象自身，那么用起来和实例对象没有区别了。
    - 退一步讲，函数拿到自身则容易循环引用，难被垃圾回收。
  - 反射
    - getattribute无法拦截特定魔术方法的调用/特殊方法隐式调用（https://docs.python.org/zh-cn/3/reference/datamodel.html#special-method-lookup ）
  - 特性
    - 推导式/生成器表达式有自身的帧栈和命名空间

**Comment by c1ino** [comment]
- [ ] py 语言设计与局限
  - py GIL（https://docs.python.org/zh-cn/3/faq/library.html#can-t-we-get-rid-of-the-global-interpreter-lock ）
    - GIL是并行阻力
    - 动态语言的运行时有很多共享的状态，难以并行
  - py 隔离与安全
    - py 没有隔离沙箱
      - https://hackernoon.com/python-sandbox-escape-via-a-memory-corruption-bug-19dde4d5fea5
    - py 没有虚拟机字节码检查（https://bugs.python.org/issue42422 ）
    - py 没有软件包环境隔离（只能依靠虚拟环境）
  - py 异步
    - py 没有针对异步设计，导致新异步生态兼容麻烦，异步api(asyncio)设计复杂繁琐
  - py 性能上限低
    - py C扩展、GIL、CPython
  - py 生态社区与发展方向
    - py 简单上手灵活通用，导致社区用户被分散到不同领域，作为脚本语言也往胶水方向发展
    - py 缺乏商业公司和市场需求作为后盾和动力，工程技术会相对不成熟（e.g.构建打包部署）
    - py 依赖开源社区，语言发展取决于开源参与度
    - py 经历2与3的撕裂，影响社区生态和信心
  - py 打包与终端用户应用分发
    - py 运行时环境设计不够轻量，不容易集成到应用中一起分发
    - py 支持c扩展模块，导致打包情况更加复杂
    - py 是动态语言，导致依赖分析困难
  - py 源码保护
    - py 没有编译，虽然有第三方源码保护库，但缺乏天然的源码混淆加密，不利于商业软件
    - py 模块有代码编译缓存（pyc），但容易还原
  - py 库/软件包安装
    - 只有全局安装，没有项目级隔离
    - 已安装库，不可导出成安装包再安装

**Comment by c1ino** [comment]
- [ ] py 类型
    - 动态强类型：运行时期类型检查
    - 类型二维图？
      - 强弱：是否类型检查
        - 变量操作/运算合法性检查，类似函数实参类型检查
        - 显式/隐式类型转换？ 
      - 动静：运行时还是编译时决定类型
      - 显式类型声明，隐式类型推导？
-  [ ] py 的面向对象与类型系统
    - https://zh.wikipedia.org/wiki/%E5%85%83%E7%B1%BB
- [ ] py 鸭子类型协议
  - 迭代协议/for-in/iter()：`__iter__`
    - types.Sequence、range、可迭代
  - 迭代器协议/next()：`__next__`
    - 迭代器、生成器、生成器表达式
  - 对象/命名空间协议/属性访问：`__***attr__`
    - 描述器协议/动态属性
  - 容器协议：`__***item__`
  - 调用协议/可调用：`__call__`
  - 类创建协议/生命周期
  - 上下文管理器协议
  - 异步/协程协议
  - 泛型协议
  - 可哈希：`__hash__`
  - 文件路径：`__fspath__ `
- [ ] py 魔术方法 运算符协议
  - in/contains
  -  算术、原地运算、位运算
  - 实例/子类检查/isinstance/issubclass
  - 比较
- [ ] py 魔术方法
  - 鸭子类型
  - 运算符协议
  - 特殊属性：slots、match_args
  - 内置函数
  - 语句

https://www.kawabangga.com/posts/3228
https://speakerdeck.com/laixintao/python-wen-hua-zhong-de-jie-kou-he-xie-yi

- 鸭子类型本质上是宽松的类型约定，不需要继承的子类
 - 或说，鸭子类型是一种检查，不检查类继承而是检查是否有实现特定方法/行为/接口
 - 或说，类继承是一种严格的静态检查，鸭子类型是宽松的动态检查
   - 在 py 中没法动态修改一个对象的类继承关系。
 - 好处是灵活弹性（运行时特性），不需要繁琐的多重继承就可以支持多种类型的接口
 - 或说，OOP是基于继承的类，鸭子类型是基于接口协议的类

https://docs.python.org/zh-cn/3/glossary.html#term-duck-typing
https://docs.python.org/zh-cn/3/glossary.html#term-special-method
https://docs.python.org/zh-cn/3/reference/datamodel.html#special-method-names
https://zh.wikipedia.org/wiki/%E9%B8%AD%E5%AD%90%E7%B1%BB%E5%9E%8B

**Comment by c1ino** [comment]
- [ ] Personal PyPI
### shell
- pyp
- poline
- oilshell/oil
- xonsh
### programming
- flpc
- taichi
- dg
- coconut
- mingshe
### pypi-stats
- pepy.tech
- pythonwheels.com
### project
- poetry/poet, pdm
- flit
- tox
- cookiecutter
- pep517
- pipreqs, pipenv, pipx, pyvenv, pip-tools, pipdeptree
### cheatsheet
- comprehensive python cheatsheet
### types 
- monkeytype
### AST
- instaviz
### stdlib
- python -m pydoc
- python -m http.server
- python -m json.tool
- python -m pdb
- python -m mimetypes
### transpiling
- golang/grumpy
- c/prometeo
- cpp/shedskin
### backport
- nvbn/py-backwards
### pattern-matching
- pampy
- patma
- moshmosh
### formatter
- yapf
- flake8, black, pylint
### game
- pygame
- pyxel

**Comment by c1ino** [comment]
- [ ] py GIL
  - no-gil
    - https://github.com/colesbury/nogil
    - https://mail.python.org/archives/list/python-dev@python.org/thread/ABR2L6BENNA6UPSPKV474HCS4LWT26GY/
 

https://python3-cookbook.readthedocs.io/zh_CN/latest/c12/p09_dealing_with_gil_stop_worring_about_it.html
http://www.dabeaz.com/GIL/
https://speakerdeck.com/dabeaz/in-search-of-the-perfect-global-interpreter-lock
