### ISSUE TITLE
[todo] 211030

### ISSUE THREAD

**Issue by c1ino** [c1ino/c1ino#10]
- [ ] 串行并发并行、同步异步、行程协程

**Comment by c1ino** [comment]
- [ ] 串行并发并行、同步异步、行程协程、同步原语、单工多工
- 同步原语
  - 信号：锁、信号量、事件
  - 消息：队列/频道/管道
- 行程协程
  - 协程
    - 同步协程 subroutine
    - 异步协程 coroutine
  - 行程
- 同步异步
  - 异步：发送不确认（单向/非阻塞）
  - 同步：发送并确认（双向/阻塞）
- 单工多工（任务）
  - 单核单任务
  - 单核多任务：时分复用
  - 单工双工（通信）

------
费林分类法
- 单核单任务：串行
- 单核多任务：并发
- 多核多任务：并行
- 多核单任务：GIL/同步锁/竞态条件

费林分类法
- MISD：单数据流不同指令并行

------
任务分解：
- 横向/范围分解：
- 纵向/功能分解：

**Comment by c1ino** [comment]
- [ ] py 学习曲线
- 语法糖：描述器、装饰器、推导式/生成器表达式、上下文管理器、匿名函数
- 迷你语言：字符串格式规范、模式匹配
- 规则：魔术方法/特殊方法、LEGB作用域
- 一等对象：迭代器/生成器/协程
- 元编程：元类、自省、反射、ast/dis
- 系统：模块导入系统、类型系统、代码字节码、命名空间
- 电池：内置模块/类型/函数、标准库
- 软件：C扩展、包管理、编程范式、设计模式
- 并发并行：无栈/有栈协程、多线程、子解释器/多进程/IPC、GIL

> ![python](https://user-images.githubusercontent.com/52480090/141672023-a7d78188-3d53-4f2b-8f6f-0e6cd4221160.png)
>https://github.com/Dobiasd/articles/raw/master/programming_language_learning_curves/python.png
>https://github.com/Dobiasd/articles/blob/master/programming_language_learning_curves.md

- 标准库：
  - 格式解析、数据结构、通信协议、运行时工具、算法工具、语言服务
  - 文件系统、文件格式、持久化、操作系统、命令行/GUI
  - 并发并行、国际化、框架、开发工具、调试分析、打包分发
- 编程范式
  - FP/函数式
  - OOP/面向对象
    - 成员属性方法、继承组合多态、……
- 常识：异常捕获、面向对象、文本编码、I/O、文件系统、函数、标识符变量值

**Comment by c1ino** [comment]
- [ ] 常见编程语言及其产物
- go: docker, k8s, twitch(部分), uber(部分), gitlab(部分)
- ruby: homebrew, jekyll, (计算的本质编程示范)
  - ror: github, twitter(前期), userstyle/greasyfork
- php: wordpress, wikipedia(mediawiki)
- python: youtube(前期), instgram(前期), pypi(pyramid), openstack, quora, zope, douban(部分), zhihu(前期), dropbox(部分), calibre, (socket编程示范), freecad(插件)
- c#: unity, linq
- rust: deno, discord(部分)
- android: java, kotlin
  - java: minecraft, jetbrains/pycharm/intellijidea
- apple: objective-c, swift
- lua(dsl): Roblox, Factorio(mod), nginx, mpv/vlc, redis
###
- anything: c/c++, javascript, java
- markup: html/css/xml, latex, json/ini/yaml/toml, markdown/rst
- dsl: sql, regular, shell/powershell/batch/awk, makefile/cmake
- others: vb/vba, perl, matlab, tcl/tk, julia, smalltalk, D
- FP: lisp/scheme/clojure/racket, scala, haskell, erlang/elixir, R, wolfram
- family: js/typescript/dart, java/scala/kotlin/groovy/clojure
- uncommon: basic, pascal/delphi, fortran, cobol, ada
- script: ahk, epl, applescript

**Comment by c1ino** [comment]
- [ ] 编程语言框架笔记
- 【词法】变量命名、字面量、作用域
  - 【数据结构】类型、内存管理（生命周期）、数据模型、一等公民
- 【句法】关键字、运算符
- 【范式】FP/OOP/声明式/命令式
- 【语法糖/盐】
- 【风格、特性】术语、访问控制、泛型、并发、协程、异步
- 【元编程】自省、反射、元类、宏、DSL
- 【底层、性能】实现、运行时库、编译链、JIT、GIL、VM、架构、移植性
- 【实践】代码组织、CLI、环境、内置/标准库、社区、陷阱误区、技巧、设计模式
- 【工程】项目管理、包管理、生态领域、安全性、调试测试、可维护性、模块化解耦
- 【基础知识】算法、计算机原理、操作系统/shell
- 【设计】语法分析、PEG/CFG、BNF

**Comment by c1ino** [comment]
- [ ] 社交通讯与数据通信表面上的共同点
1. 社交通讯、SNS、IM、email：消息通讯
2. 消息聚合：RSS
3. 数据通信、并行编程、并发模型：消息传递（Actor、CSP、分布式消息队列）、共享内存（锁、信号）

**Comment by c1ino** [comment]
- [ ] 浏览器(内核)与游戏引擎表面上的共同点
- 都含有渲染引擎、都负责渲染工作。
- 不同点：浏览器(内核)更偏向文字性、GUI、排版性的渲染；游戏引擎更偏向图形性、动态性、空间运动、物理的渲染。
- 发散：浏览器(内核)和游戏引擎可以视作一体两面，两者都属于“渲染层”，下方是图形引擎/库，上方是应用层。
- 相关：
  - toutiao.io/posts/zizo8yy

---
视觉引擎
- 富文本、排版、图像、媒体、2D
- 图形、动画、顶点、3D

**Comment by c1ino** [comment]
- [ ] 模式(pattern)与模型(model)
- 二维模式（图形样式）、三维模型
- 二维 = 一维+时间 | 二维平面

**Comment by c1ino** [comment]
- [ ] py元类与继承的主要区别
- 继承：父类、基类、超类
- 父类：静态继承（mro/super命名空间链）
- 元类：动态构造（类对象工厂）
- 类：（对象工厂）
- 实例：（对象）

**Comment by c1ino** [comment]
- [ ] pyqt history
- nokia, pyside, anki

**Comment by c1ino** [comment]
- [ ] 互联网内容的语言
- >第二热门的多字节编码方式Shift JIS和GB 2312分别具有0.3％和0.2％的占有率。
  >https://zh.wikipedia.org/wiki/UTF-8

**Comment by c1ino** [comment]
- [ ] py list comp & map
- 推导式本质和map一样，只能映射不能访问之前的元素
  - 访问之前的元素，类似的功能有functools.reduce
- 推导式和lambda都只允许表达式。推导式的if相似于filter
- 严格来说map和生成器表达式相似（两者都是生成器？）

**Comment by c1ino** [comment]
- [ ] 二进制以此类推
- 二元：有、无
- 三元：小于、等于、大于
  - 向量：正、零、负
- 四元：无边、双向边、左单向边、右单向边

**Comment by c1ino** [comment]
- [ ] CS大纲拼图
- 编程（软件）
  - 编程、算法、数据结构
  - 语言、程序、编译原理
    - SICP、龙书、虎书、鲸书
  - 数据库
  - 软件工程、人机交互
- 系统（环境、上下文）
  - 组成原理、架构
  - 操作系统、shell
- 通信（传输）
  - 网络、协议、路由、信息论
- 安全（矛与盾）
  - 密码学、信息安全、逆向工程、黑客
- web（网络）
  - HTTP、WWW、DNS、网站、服务器、浏览器
    - html、css、javascript、前端、后端
  - 分布式、并发、集群、云计算
- 数学（细节）
  - 线性代数、离散数学、微积分、统计学、（数学工具/算法）
- 硬件（底层、性能）
  - 物理学、存储介质、显示面板、集成电路、半导体、材料学
- IT（应用）
  - 信息检索、信息管理、信息备份、信息保护
  - 通信技术、通信安全、系统安全、系统运维
  - 软件开发、软件应用、项目管理、业务管理
- 选修
  - 图形学、多媒体编码压缩
    - VR/AR/元宇宙、建模/渲染/特效、流媒体编码
    - 着色器、GLSL、CUDA
  - 机器学习、大数据
    - 人工智能、计算机视觉、自然语言
  - 嵌入式、物联网、机器人
  - 物理演算、CAD、量子计算
  - 区块链、密码学货币、挖矿、POW/POS、合约
  - 电子商务/金融、电子支付
- 概略
  - IT、软件、系统、硬件
  - 网络、通信
  - 安全
  - 数学


[模板:计算机科学 - 维基百科]:(https://zh.wikipedia.org/wiki/Template:電腦科學)

**Comment by c1ino** [comment]
- [ ] 模式匹配
- regular-expression/regex/re
  - 字符串模式匹配ast
  - 词法分析
- 静态匹配（hash）
- 前缀匹配/正向、后缀匹配/反向（trie）
- 中缀匹配/子串（kmp）
- 路径匹配/路由（radix trie）
- 通配匹配/捕获（glob/regex）

**Comment by c1ino** [comment]
- [ ] py类对象创建流程
>https://docs.python.org/zh-cn/3/reference/datamodel.html#customizing-class-creation
```py
@decorator
class Child(Base, metaclass=MetaChild):
    # body
    pass
```
- class Child(Base, metaclass=MetaChild):
    1. MetaChild.__prepare__(...)
        - (name, Bases, **kwds) -> namespace
    2. Child.body()
        - exec(body, globals(), namespace)
    3. MetaChild(...)
        - (name, Bases, namespace, **kwds) -> Child
        - MetaChild.__new__(...) 
            - type.__new__(...)
                - (descriptor_hook(...))
                - Base.__init_subclass__(...)
        - MetaChild.__init__(???)
    4. decorator(...)
        - (Child) -> Child

# 
- QA
  - 自定义元类的父类不能派生子类？
     `TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases`
    >最近派生的元类会从显式指定的元类（如果有）以及所有指定的基类的元类（即 type(cls)）中选取。最近派生的元类应为 所有 这些候选元类的一个子类型。如果没有一个候选元类符合该条件，则类定义将失败并抛出 TypeError。
    >https://docs.python.org/zh-cn/3/reference/datamodel.html#determining-the-appropriate-metaclass 
    - 可能是因为子类的元类也必须与父类的元类保持派生关系？

**Comment by c1ino** [comment]
- [ ] 科学树大纲拼图
- 数学 (Mathematics)
  - 纯数学
    - 应用数学
      - 计算数学 (computational)
        - 运算科学 (computing)
  - 逻辑学
    - 计算科学 (computation/TCS)
      - 计算机科学 (computer)
  - 统计学
    - 经济学 (Economy)
      - 金融学 
  - 自然科学 (Science)
    - 应用科学 (Technology)
      - 工程学 (Engineering)
- 哲学
  - 人文科学 (Humanities)
    - 社会科学 (Social Sciences)
    - 艺术 (Arts)
##
- 哲学 （+逻辑学）
  - 科学 （+数学）
    - 系统科学
    - 技术科学
    - 工程技术
- 科学(Science) （+数学(Mathematics)）
  - 系统科学 (System)
  - 技术科学 (Technology)
  - 工程技术 (Engineering)


[工程科学、工程学]:工程技术
[理科、文科、武科]:\
[科学、工艺、哲学]:\
[STEM]:\
[SHAPE/HASS]:\
##
- [学术领域大纲 - 维基百科](https://zh.wikipedia.org/wiki/学术领域大纲)
- [学科分类与代码国家标准 | 模板:GB/T 13745 - 维基百科](https://zh.wikipedia.org/wiki/Template:GB/T_13745)
- [数学学科分类标准 - 维基百科](https://zh.wikipedia.org/wiki/数学学科分类标准)
- [科学大纲 - 维基百科](https://zh.wikipedia.org/wiki/科学大纲)

**Comment by c1ino** [comment]
- [ ] common pl
- script
    - frontend: js (vbs)
    - backend: py lua psh/bat perl shell
      - web: rb php nodejs
- compile
    - vm (bytecode): java c#
    - (machinecode): rust go cpp
- dsl
  - sql regular
  - non-pl (mime)
    - (markup) html/xml css markdown/rst 
    - (data) json ini csv yaml/toml

**Comment by c1ino** [comment]
- [ ] py版本更新后的site-packages
 - 不同版本之间不能共用site-pkgs
 - pip freeze 导出之前版本的安装包列表
 - 新版本下 pip install -r 安装包列表
   - 如果pip有下载缓存或编译缓存，会节省时间

**Comment by c1ino** [comment]
- [ ] sql/nosql的相似之处
- sql的本质是集合，nosql的本质是字典，dict的本质是{set: list} (python)
- sql元素的值是元组，nosql元素的值可以是任意容器类型
- sql像表，nosql像树

**Comment by c1ino** [comment]
- [ ] 通信公式
- 通信 = (格式 + 协议) + (信道 + 信号)
- OSI三层模型
  - 线路层/硬件（媒介、链路）[mac]【点对点】
  - 网络层/中间 [ip]【路由】
  - 传输层/软件（传输、应用）[tcp]
    - 应用层 [http]
      - 会话层、编码层 
- 模式
  - 单工、双工
  - 阻塞、非阻塞
  - 同步、异步
- 发散
  - 信息层（定性与定量）
  - 控制层（通信与反馈）
  - 系统层（网络与闭环）

**Comment by c1ino** [comment]
- [ ] css filter
- HSL/HSB
  - hue-rotate  (色相/色度)
    - invert  (反相)
  - saturate  (饱和度) 
    - grayscale  (灰阶)
      - sepia  (褐化)
  - brightness  (明度/亮度)
    - contrast  (对比度)
- opacity  (透明度)
- blur  (模糊)
- url  (svg滤镜)

**Comment by c1ino** [comment]
- [ ] 算法
- 程序设计
  - 设计模式、框架、组织结构、模型模式/系统建模、耦合内聚
    - 业务、流程、策略
      - 功能、底层、依赖
- 设计经验/道法
  - [nusr/hacker-laws-zh: 💻📖对开发人员有用的定律、理论、原则和模式。(Laws, Theories, Principles and Patterns that developers will find useful.)](https://github.com/nusr/hacker-laws-zh)
  - [HowToBeAProgrammer/11-如何学习设计技能](https://github.com/braydie/HowToBeAProgrammer/blob/master/zh/1-Beginner/Personal-Skills/11-How-to-Learn-Design-Skills.md)
  - [HowToBeAProgrammer/11-算法与数据（如何分析数据）](https://github.com/braydie/HowToBeAProgrammer/blob/master/zh/2-Intermediate/Personal-Skills/11-How-to-analyze-data.md)
  - ~~[Growth: 全栈增长工程师指南 – 重构到设计模式](https://growth.phodal.com/#重构到设计模式)~~
  - ~~[Growth: 全栈增长工程师指南 – 架构模式](https://growth.phodal.com/#架构模式)~~
  - ~~[RePractise – 模式篇设计与架构](http://repractise.phodal.com/#模式篇设计与架构)~~
- 结构
  - 小结构
    - 数据结构
  - 中结构
    - 程序结构、算法结构、流程结构
  - 大结构
    - 软件结构、服务结构、系统结构

**Comment by c1ino** [comment]
- [ ] software-development
1. programming language
    - syntax / grammar 
    - paradigm / feature
    - api / builtins / stdlib
    - style / zen
    - design / model
2. environment / runtime
    - install
    - cli / config
    - package-mangager
    - extension / ffi
3. software-engineering / develop
    - scm/vcs, sdk, toolchain/scaffolding
    - debug, unit-test, skills/techniques
    - deployment, distribution
    - architecture, design-pattern, security
    - ...
4. best-practice / coding-style / trick
5. programming / universal / basic / common
    - background / shell / system / layer
    - data-struct / algorithm / mathematics
6. upstream / implement / low-level / contribute
---
### software / application / service
- develop
  - programming 
  - design / debugging / testing / maintenance / security
- deployment
  - distribution
  - (fix / patch / upgrade)
- operations
  - environment configuration
#### prgramming
- IPO  / ((inner/content))
  - data + code
    - data-struct / algorithm
- struct / model  / ((inter/file))
- organization / hierarchy  / ((outer/file-system))

[file-format?]:\

---
1. programming
    - data-struct / algorithm 
3. programming language
    - syntax / style / builtins
5. runtime / environment / extension
    - shell / cli / gui / config
    - requirement / dependent
      - library / package
7. software
    - develop / deployment / operations

**Comment by c1ino** [comment]
- [ ] “结构化”
- 结构化：可（编程）访问
  - 文字/文本/数值
  - 非结构化：（转为）图像/媒体
    - 反非结构化：ocr, cv
  - （“结构化”程度是相对的，不是非黑即白二分法）
    - 例如，文本文字比文本图片更结构化，但数据库比文本更结构化。可以再细分下去。
    - 又例如序列化和反序列化，内存中的变量对象序列化成二进制格式则可访问性变差，需要反序列化才能解读访问。
  - （越结构化则（编程）可访问性越好，反之越差）
  - （结构化数据的载体就是容器/格式/“数据结构”）
- 自然/编程语言的“结构”：语法结构/ast

---
---
---
- [什么是结构化数据？– 结构化数据简介 – AWS](https://aws.amazon.com/cn/what-is/structured-data/)
- [Demystifying Text Data with the unstructured Python Library (+alternatives) | Saeed Esmaili](https://saeedesmaili.com/demystifying-text-data-with-the-unstructured-python-library/)

**Comment by c1ino** [comment]
- [ ] 模板引擎
- 模板的目的是对硬编码数据替换的简化，因为软编码数据的替换本就可以由程序/软件自己做到 
- 硬编码数据例如：文件路径、源码
- 模板举例：编译宏/预处理、网页模板、字符串模板、项目模板
- 模板与shell的共同点
  - 都是基于文本的替换、插值
  - 都喜欢用管道语法
- 模板用于源码就是代码生成器，用于网页就是html代码生成器
- 通常用途：
  - 字符串模板/格式化（文本模板）
  - 模板文件（网页模板）
  - 文件夹/文件树模板（项目模板）
